window.OB_releaseVer="107493";OBR=window.OBR||{};OBR.h=OBR.h||[];OBR.ma=OBR.ma||{};window.OBR$=function(c){return document.getElementById(c)};OBR.c=OBR.c||function(){var c={},a={};a.I=function(){return c};a.i=function(h){c.U=h;c.ka=[];c.Oa=(new Date).getTime()};a.Oa=function(){return c.Oa};a.log=function(h){var d=((new Date).getTime()-c.Oa)/1E3;c.ka.length<1E3&&c.ka.push(d+" >"+h)};a.printLog=function(){if(c.U.b.Be)window.console.log(c.ka.join("\n"));else{var h=c.U.a.za();if(h){h.innerHTML=c.ka.join("<br>");h.style.display="block"}}return c.ka.join("\n")};a.i(OBR);return a}();OBR.printLog=OBR.c.printLog;OBR.a=OBR.a||function(){var c={},a={},h=document,d=OBR;a.I=function(){c.U=d;return c};a.i=function(b){d=b};a.X=function(){return function(){}};a.re=function(){var b=window.jQuery;if(b!==undefined)return!(/1\.(0|1|2|3|4)\.(0|1)/.test(b.fn.jquery)||/^1\.1/.test(b.fn.jquery)||/^1\.2/.test(b.fn.jquery)||/^1\.3/.test(b.fn.jquery));return false};a.$=function(b){if(b!==null&&!isNaN(b))return d.o("outbrain_widget_"+b);return null};a.za=function(){return d.o("ob_holder")||false};a.hb=function(){if(!d.o(d.b.eb)){var b=
d.a.createElement("iframe",d.b.eb),e=b.style;e.display="none";e.width="1px";e.height="1px";b.src="about:blank";(e=a.za())||(e=a.Wd());d.a.gb(b,e)}};a.Wd=function(){if(h.body)return h.body;var b;b=d.a.ya("","","body",true);return b.length<=0?h.lastChild:b[0]};a.createElement=function(b,e){b=h.createElement(b);b.setAttribute("id",e);return b};a.fb=function(b){if(d.b.od===d.b.Eb)try{document.createStyleSheet().cssText=b}catch(e){}else{var f=h.createElement("style"),g=typeof h.body.style.WebkitAppearance===
"string";f.type="text/css";h.getElementsByTagName("head")[0].appendChild(f);f[g?"innerText":"innerHTML"]=b}};a.z=function(b,e,f){b=h.createElement("script");b.type=d.b.Oe;b.src=e;b.async=!!f;b.defer=false;return b};a.lg=function(b,e){b=d.a.createElement("link",b);b.setAttribute("rel","stylesheet");b.setAttribute("type",d.b.Fd);e&&b.setAttribute("href",e);return b};a.xd=function(b){var e=d.o("ob_iframe");if(e)e.src=b};a.xc=function(b){b=isNaN(b)?1E5:b;return Math.floor(Math.random()*b)};a.wf=function(b,
e,f){return b.replace(e,f)};a.je=function(b){var e=[];e.push('<script type="text/javascript">');e.push("(function(){var ob=document.createElement('script');ob.async=true;ob.src='"+b+"';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(ob,s);}());");e.push("window.OBR={extern:{}};");e.push("OBR.extern.returnedHtmlData=function(json,idx){(top.OBR.extern.returnedHtmlData)&& top.OBR.extern.returnedHtmlData(json,idx); };");e.push("OBR.extern.returnedIrdData=function(json,idx){(top.OBR.extern.returnedIrdData)&& top.OBR.extern.returnedIrdData (json,idx);};");
e.push("OBR.extern.returnedJsonData=function(json,idx){(top.OBR.extern.returnedJsonData)&& top.OBR.extern.returnedJsonData(json,idx);};");e.push("OBR.extern.returnedError=function(json){(top.OBR.extern.returnedError)&& top.OBR.extern.returnedError(json);};");e.push("window.outbrain={};");e.push("outbrain.returnedIrdJsonData=function(json,idx){(top.outbrain.returnedIrdJsonData) && top.outbrain.returnedIrdJsonData(json,idx);  };");e.push("outbrain.returnedJsonData =function(json,idx){(top.outbrain.returnedJsonData) && top.outbrain.returnedJsonData(json,idx); };");
e.push("outbrain.returnedError=function(json){(top.outbrain.returnedError) && top.outbrain.returnedError(json);};");e.push("<\/script>");return e.join("")};a.ie=function(){var b;if(OBR.o("objsonpp"))return OBR.o("objsonpp");b=document.createElement("iframe");b.id="objsonpp";b.name="objsonpp";b.ng="0";b.width="1";b.height="1";b.border="0";if(b.Bf)b.Bf="seamless";(b.frameElement||b).style.cssText="width:0;height:0;border:0;";document.body.appendChild(b);return b};a.ye=function(b){var e=a.ie();e=e.contentWindow||
e.contentDocument;if(e.document)e=e.document;e.open();e.write(b);e.close()};a.v=function(b,e,f){var g=d.b.Ya;if(d.b.Fa&&e){d.c.log("using advanceLoader");d.c.log("using: "+b.getAttribute("src"));b=a.je(b.getAttribute("src"));a.ye(b)}else a.Ae(b,f,g)};a.Ae=function(b,e,f){var g,i;g=f||d.b.Ya;a.A(b,"error",function(k){d.c.log("insertToHeadStandard onError");var l=g.parentNode||window;k=k||l.event;b.onerror=null;e&&e.call(d.b.Ya,k)});f=g.getElementsByTagName("head");try{if(f&&f.length>0)f[0].insertBefore(b,
f[0].firstChild);else{i=g.getElementsByTagName("script");i[0].insertBefore(b,i[0].firstChild)}}catch(j){d.c.log("Err insertToHead:"+j)}};a.P=function(b){return encodeURIComponent(b)};a.ya=function(b,e,f,g){f=f||"*";g=!!g;var i=[];f=h.getElementsByTagName(f);var j,k,l;j=0;for(k=f.length;j<k;j+=1){l=b==="class"?f[j].className:f[j].getAttribute(b);(l=b===""?true:g?l.indexOf(e)>-1:l===e)&&i.push(f[j])}return i};a.oa=function(b,e,f){if(b.detachEvent)b.detachEvent("on"+e,f);else b.removeEventListener&&
b.removeEventListener(e,f,false)};a.A=function(b,e,f){if(b.attachEvent)b.attachEvent("on"+e,function(){f.call(b)});else b.addEventListener&&b.addEventListener(e,f,false)};a.gb=function(b,e){try{e.appendChild(b)}catch(f){d.c.log("fail insert into Dom:"+f)}};a.La=function(b){if(b=d.o(b))try{b.parentNode.removeChild(b)}catch(e){}};a.insertBefore=function(b,e){return e.parentNode.insertBefore(b,e)};a.rg=function(b){if(b instanceof Array)return true;return Object.prototype.toString.call(b)==="[object Array]"};
a.Pa=function(b,e){var f=/htt(p|ps)?:\/\/127\.0\.0\.1(:\d\d\d\d)?$/i;if(/htt(p|ps)?:\/\/([\w\-]*|[\w\-]*\.[\w\-]*)\.outbrain\.com(:\d\d\d\d)?$/i.test(b)||f.test(b))return b;return e};a.Zf=function(b){var e=h.createElement("div");e.innerHTML=b;return e.childNodes};a.B=function(b,e){if(b)return b.getAttribute(e);return null};a.w=function(b,e,f){b&&b.setAttribute(e,f)};a.hd=function(b,e){if(b)b.className+=" "+e;return null};a.J=function(b,e){b=b.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var f,g,i;
try{f="[\\?&]"+b+"=([^&#]*)";g=new RegExp(f,"i");i=g.exec(window.location.href);if(i===null)return e;return i[1]}catch(j){return e}};a.Bd=function(b){if(typeof b==="string"&&b.indexOf("#")>0)b=b.substr(0,b.lastIndexOf("#"));return b};a.Mb=function(b){var e=d.b.fa+"/strip_default.png";if(b.src!==e){b.alt="";b.title="";b.src=e}};a.Nd=function(){var b=null,e,f,g=null;if(typeof window.OB_MP_feed==="string")b=window.OB_MP_feed;else if((e=h.getElementsByTagName("head"))&&e.length>0){f=e[0].getElementsByTagName("link");
for(e=0;e<f.length;e+=1){g=f[e];if(g.type!==null&&(g.type==="application/rss+xml"||g.type==="application/atom+xml")&&g.href!==null&&g.href!==""){b=g.href;break}}}return b};a.bc=function(b,e){var f=null;if(b.currentStyle)f=b.currentStyle[e];else if(window.getComputedStyle)f=document.defaultView.getComputedStyle(b,null).getPropertyValue(e);return f};a.Ff=function(){var b=a.za(),e,f;if(b){e=d.a.createElement("span","ob_a");a.insertBefore(e,b);e.innerHTML=".";f=a.bc(e,"color");a.La("ob_a");e=d.a.createElement("a",
"ob_a");e.setAttribute("href","void(0)");e.innerHTML=".";a.insertBefore(e,b);b=a.bc(e,"color");a.La("ob_a");f=f==="rgb(0, 0, 0)"||f==="#000000"?"#555":f;a.fb(".ob-tcolor{color:"+f+"} .ob-lcolor{color:"+b+"} .ob-bgtcolor{background-color:"+f+"} .item-link-container:hover .ob-tcolor{border-color:"+f+"}")}};a.fe=function(){var b=a.$b("property","og:url","meta",false,"content");if(b===null)b=a.$b("rel","canonical","link",false,"href");if(b===null)b=window.location.href;return b};a.$b=function(b,e,f,g,
i){var j=null;b=a.ya(b,e,f,g);if(b!==null&&b.length>0)j=b[0].getAttribute(i);return j};a.yd=function(b){var e,f,g;f=d.h[b].l("tracking",false);e=d.b.Ga;b=d.h[b].l("comScoreEnabled",true);g=d.b.Nb;if(f===false&&e===false&&b===true&&g===false){a.hb();if(e=d.o(d.b.eb)){e.src=d.b.fa+"/"+d.b.nb+"3rd/comScore/comScore.htm";d.b.Nb=true}}};a.pe=function(){var b=a.cb(8),e="";if(typeof window.name==="string"&&(window.name===""||window.name.indexOf("frame")>-1)){window.name=b;e=window.name}else e=typeof window.name===
"string"&&window.name!==""?window.name:b;return e};a.cb=function(b){var e="",f;b=typeof b==="number"?b:8;for(f=0;f<b;f+=1)e+="0123456789ABCDEFGHIJKLMNOPQRSTUVWXTZabcdefghiklmnopqrstuvwxyz".charAt(Math.floor(Math.random()*61));return e};a.bb=function(b){var e;for(e in d.ma)if(d.ma[e].g===b)return d.ma[e];return null};a.qg=function(b){var e,f;f=d.h;for(e=0;e<f.length;e+=1)if(f[e].ja()===b)return f[e];return null};a.Je=function(b){var e;for(e in b)if(b.hasOwnProperty(e))return false;return true};a.Y=
function(b,e){if(typeof b!=="function")return null;if(typeof e==="undefined")return b();return b(e)};a.Hd=function(b,e){return b*e};a.ae=function(b){if(!b||b==="")return[];b=b.replace("","").replace("http://","").replace("https://","").replace("www.","").replace("www2.","").split("/");b.pop();if(b.length>0)return b;return[]};a.be=function(b,e){b=a.ae(b);var f=[],g="";if(e>=b.length)g=b.join(".");else{f[0]=b[0];for(g=1;g<=e;g+=1)f[g]=b[g];g=f.join(".")}return g};a.i(OBR);return a}();
OBR.G=function(c,a,h,d,b,e,f,g,i){var j,k;j=this;k=0;i=typeof i==="function"?i:OBR.a.Hd;j.start=function(){var l;k+=1;if(OBR.a.Y(c,k))OBR.a.Y(a,k);else if(l=OBR.a.Y(g,k))OBR.a.Y(d,k);else if(l=k===e&&e!==1E3)OBR.a.Y(d,k);else{OBR.a.Y(h,k);l=f?i(k,b):b;setTimeout(function(){j.start()},l)}};j.start()};OBR.Rb=OBR.Rb||function(){var c={};c.De=function(){return document.readyState==="complete"};return c}();
OBR.Q=function(){var c={},a=[];c.add=function(h,d){if(typeof h==="string"&&typeof d==="function"){var b={};b.name=h;b.Ud=d;a.push(b)}};c.k=function(h){OBR.c.log("event fire:"+h);var d=[],b,e;for(b=1;b<arguments.length;b+=1)d.push(arguments[b]);e=a.length;for(b=0;b<e;b+=1)if(a[b]&&a[b].name&&a[b].name===h)try{a[b].Ud.apply(this,d)}catch(f){OBR.c.log("fire evnt err: "+f)}};c.oa=function(h){OBR.c.log("remove event :"+h);var d,b;b=a.length;for(d=0;d<b;d+=1)if(a[d]&&a[d].name&&a[d].name===h)try{a.splice(d,
1)}catch(e){OBR.c.log("rm evnt err: "+e)}};c.H=function(){a=[]};return c};OBR.Md=function(c){return new c.Q};OBR.Pd=function(){var c={},a=[];c.add=function(h){a.push(h)};c.top=function(){return a.length>0?a.shift():null};c.Ad=function(){a=[]};return c};OBR.b=OBR.b||function(){var c={},a={},h=OBR,d;a.bd="opera";a.Eb="msie";a.Wc="firefox";a.Vc="chrome";a.gg="safari";a.Zc="mozilla";a.kg="boolean";a.Fg="string";a.yg="object";a.Gg="undefined";a.eb="ob_iframe";a.ec=true;a.vc=0;a.yb="outbrain_widget_";a.Oe="text/javascript";a.Fd="text/css";a.Ya=document;a.ic=typeof document.createElement("script").async!=="undefined";a.Tc=h.a.pe();a.uf=document.referrer;a.tf=h.a.P(document.referrer);a.Re=document.location.href;a.ug=h.a.P(a.Re);a.va=false;a.md=navigator.userAgent.toLowerCase();
a.Cg=navigator.platform.toLowerCase();d=a.md;a.od=/opera/.test(d)?a.bd:/msie/.test(d)?a.Eb:/firefox/.test(d)?a.Wc:/chrome/.test(d)?a.Vc:/safari/.test(d)?a.Dg:a.Zc;a.Ga=!!/(iphone|ipod|symbian|android|windows ce|blackberry|palm|ipad)/.test(d);a.He=0;a.Ge=function(){return window.XMLHttpRequest===undefined&&ActiveXObject!==undefined};a.of=window.OB_platformType||null;a.Ia=typeof a.of==="number";a.Hc=null;a.Sb=null;a.Yf=function(){if(a.Ia&&a.Hc&&a.Sb){a.Hc();a.Sb()}};a.sa=typeof window.OB_releaseVer===
"string"?window.OB_releaseVer:"0";a.We=window.OB_disable_odbl===true;d=("https:"===document.location.protocol?"https":"http")+"://";a.ud="/blogutils/ExcludeRec.action?bocr=";a.zg="html";a.te=h.a.Pa(h.a.J("wiodb",d+"hpr.outbrain.com"),d+"hpr.outbrain.com");a.ob=h.a.Pa(h.a.J("wiodb",d+"odb.outbrain.com"),d+"odb.outbrain.com");a.vd="https://web.archive.org/web/20130607073046/http://storage.outbrain.com/";a.fa=h.a.Pa(h.a.J("wihost",d+"widgets.outbrain.com"),d+"widgets.outbrain.com");a.jf=h.a.Pa(h.a.J("wiout",d+"outbrain.com"),d+"outbrain.com");
a.uc=d+"log.outbrain.com/";a.nb="nanoWidget/";a.kf=a.Ia?"NANOWDGTLT13":"NANOWDGT01";a.Te=a.fa+"/"+a.nb+a.sa+(a.Ia?"/moduleLT":"/module");a.Be=typeof window.console==="object";a.Nc=h.a.Bd(h.a.Nd());a.Mc=a.Nc===null?"":h.a.P(a.Nc);a.Nb=false;a.Xe=h.a.J("obdraft",false)==="true"?"&obDraft=true":"";a.gd=h.a.J("obAbtest",false)!==false?"&obAbtest="+h.a.J("obAbtest",""):"";a.Kc=function(b){a.Fa=a.Fa||b;return a.Fa};a.Fa=a.Kc(h.a.J("advanceLoader","false").toLowerCase()==="true");a.nc=0;a.la=null;a.I=function(){c.U=
h;return c};return a}();OBR.e=OBR.e||function(){var c={},a,h={};c.i=function(b,e){a=b;c.sf(e)};var d={Fb:0,Yc:1,Db:2};c.j={Ua:"POPUPDESCRIPTION",ua:"WIDGETSTATISTICS",ta:"WHATIS",Sa:"FLYTHROUGH",Va:"VIDEOPLUGIN",ga:"POSCUL"};c.dd=function(b,e,f){var g={Gd:b,url:e,version:f,ra:d.Fb,Wa:null,Ob:this};g.zd=function(){if(g.ra===d.Db)g.lc();else if(g.ra===d.Fb){var i=OBR.a.z("module_Call_"+g.Gd,g.url,true);g.ra=d.Yc;OBR.a.v(i,false)}};g.lc=function(){g.ra=d.Db;typeof g.Wa==="function"&&g.Wa.call(g.Ob)};return g};c.sf=function(b){function e(g,
i,j){b[g]||(b[g]=new c.dd(g,i,j))}function f(g){return a.b.Te+"/"+g}e(c.j.Ua,f("popupDescription.js"),-1);e(c.j.ua,f("widgetStatistics.js"),-1);e(c.j.ta,f("whatis.js"),-1);e(c.j.Sa,f("flyThrough.js"),-1);e(c.j.Va,f("videoPlugin.js"),-1);e(c.j.ga,f("positionCalculation.js"),-1)};c.ge=function(b){return h[b]};c.L=function(b,e,f){if(b=c.ge(b)){b.Wa=e||OBR.a.X();b.Ob=f;b.zd()}};c.ac=function(b){return h[b].ra};c.da=function(b){a.b.sa!=="-1"&&h[b].lc()};c.i(OBR,h);return c}();OBR.i=OBR.i||void 0;OBR.o=function(c){return document.getElementById(c)};OBR.D=OBR.D||function(){var c={},a={},h,d;a.i=function(b){h=b;c.na=new h.Q;d=false};a.I=function(){return c};c.ze=function(){var b,e;b=h.a.createElement("iframe","ob_ping");b.setAttribute("id","ob_ping");b.style.border="0px";b.style.width="0px";b.style.height="0px";b.setAttribute("src",h.b.ob+"/utils/ping.html?r="+h.a.xc());h.a.A(b,"load",function(){h.c.log("ping returned");h.b.vc=2;c.na.k("success");h.D.Dc()});e=h.a.za();if(e!==null){h.c.log("ping inserted");h.a.gb(b,e)}};c.nf=function(){h.c.log("ping Wait");
new h.G(function(){return h.b.vc===2},function(){},h.a.X(),function(){c.na.k("fail");h.D.Dc()},50,200,false)};a.Dc=function(){h.a.La("ob_ping")};a.ff=function(b){c.na.add("success",b)};a.ef=function(b){c.na.add("fail",b)};a.Ke=function(){return d};a.Lc=function(b){d=typeof b==="boolean"?b:d};a.mf=function(){c.ze();c.nf()};a.u=function(){c.na.H()};a.i(OBR);return a}();OBR.Z=OBR.Z||function(){var c,a={},h={},d;a.i=function(b){c=b;d=c.Md(c)};a.I=function(){return h};h.Xa=function(b){var e,f;e=0;for(f=b.length;e<f;e+=1){c.a.w(b[e],"data-ob-mark","true");d.k("find",b[e])}};h.Xb=function(){return c.a.ya("class","OUTBRAIN","div",true)};h.$d=function(b){var e,f,g=[],i=[];e=0;for(f=b.length;e<f;e+=1)if(typeof b[e].containerId==="string")if(c.o(b[e].containerId)){var j=c.o(b[e].containerId);typeof b[e].widgetId==="string"&&c.a.w(j,"data-widget-id",b[e].widgetId);typeof b[e].permalink===
"string"&&c.a.w(j,"data-src",b[e].permalink);typeof b[e].advanceLoader==="boolean"&&c.a.w(j,"data-advance-loader",b[e].advanceLoader);typeof b[e].dynLoad==="boolean"&&c.a.w(j,"data-dynLoad",b[e].dynLoad);typeof b[e].widgetType==="string"&&c.a.w(j,"data-widget-type",b[e].widgetType);typeof b[e].timeout==="string"&&c.a.w(j,"data-timeout",b[e].timeout);typeof b[e].fbk==="string"&&c.a.w(j,"data-fbk",b[e].fbk);i.push(j)}else g.push(b[e]);window.OB_elements=g;return i};h.ke=function(){var b=[];if(typeof window.OB_elements===
"object"&&window.OB_elements.length>0)b=window.OB_elements;return b};h.he=function(){var b=[],e=h.Xb(),f,g;f=0;for(g=e.length;f<g;f+=1){var i=c.a.B(e[f],"data-ob-mark");if((i===null||i!=="true")&&e[f])b.push(e[f])}f=h.ke();if(f.length>0){c.c.log("Array of elements found!");e=h.$d(f);f=0;for(g=e.length;f<g;f+=1)b.push(e[f])}return b};a.jg=function(b){h.Ub(b)};h.Ub=function(b){if(b===undefined){var e=false;c.c.log("searching for containers");new c.G(function(){return e},c.a.X(),function(){e=c.Rb.De();
var f=h.he();e&&c.c.log("checking:("+e+")");f.length>0&&h.Xa(f)},d.k("stopSearch"),50,1E3,false)}else if((b.length||0)>0)h.Xa(b)};a.tg=function(){return h.Xb().length>0};a.$e=function(b){d.add("find",b)};a.Bg=function(b){d.add("stopSearch",b)};a.Tb=function(){h.Ub()};a.Qd=function(b){var e=[],f,g;c.r.ve();f=0;for(g=c.h.length;f<g;f+=1){var i=c.a.$(f);if(i!==null){typeof b==="string"&&c.a.w(i,"data-src",b);c.a.w(i,"data-ob-mark","false");e.push(i)}}if(e.length>0){c.h=[];h.Xa(e)}};a.u=function(){d.H();
c.h=[]};a.i(OBR);return a}();OBR.r=OBR.r||function(){var c={},a={},h;a.i=function(d){h=d;c.qb=new OBR.Pd;c.Ka=new OBR.Q;c.Ha=false};c.Vd=function(d){var b;b=d.oe();var e,f=h.a.wf;b=b&&b==="hp"?h.b.te+"/utils/get?url=$LNK$SRC&settings=$SET&recs=$REC&widgetJSId=$WID&key=$KEY&idx=$IDX&version=$VER&ref=$REF&apv=$APV&sig=$SIG&format=$FRT&rand=$RND$DRFT$ABTEST":h.b.ob+"/utils/get?url=$LNK$SRC&settings=$SET&recs=$REC&widgetJSId=$WID&key=$KEY&idx=$IDX&version=$VER&ref=$REF&apv=$APV&sig=$SIG&format=$FRT&rand=$RND$DRFT$ABTEST";e=d.ja();
b+=e!==""&&e!==null?"&fbk="+e:"";b=f(b,"$LNK",h.a.P(d.aa()));b=f(b,"$SRC",h.b.Mc.length>0?"&srcUrl="+h.b.Mc:"");b=f(b,"$IDX",d.g);b=f(b,"$SET",true);b=f(b,"$REC",true);b=f(b,"$KEY",h.b.kf);b=f(b,"$WID",d.q());b=f(b,"$VER",h.b.sa);b=f(b,"$REF",h.b.tf);b=f(b,"$SIG",h.b.Tc);b=f(b,"$APV",h.b.va);b=f(b,"$FRT",d.de());b=f(b,"$RND",h.a.xc());b=f(b,"$DRFT",h.b.Xe);return b=f(b,"$ABTEST",h.b.gd)};c.we=function(d,b){var e=h.a.z("ob_odbCall_"+b.g+b.q(),d,true);b.t.Nf();c.Ka.k("onOdbFire_"+b.g+"_"+b.q(),b);c.Ka.oa("onOdbFire_"+
b.g+"_"+b.q());b.ja()!==""?h.a.v(e,true,function(){h.W.se(b)}):h.a.v(e,true);h.c.log("fire this src "+d)};c.Of=function(d){h.b.ic&&setTimeout(function(){c.Cc(d.g,d.q())},1E4)};c.Cc=function(d,b){h.a.La("ob_odbCall_"+d+b)};a.k=function(){if(!(c.Ha===true||h.D.Ke()!==true)){c.Ha=true;var d=c.qb.top(),b;if(d){h.c.log("fire odb for "+d.aa());b=c.Vd(d);c.we(b,d);c.Of(d)}else c.Ha=false}};a.cf=function(d,b){c.Ka.add("onOdbFire_"+d.g+"_"+d.q(),b)};a.wb=function(d,b){c.Ha=false;c.Cc(d,b)};a.Ef=function(d){if(d===
true)OBR.b.va=d};a.ve=function(){OBR.b.va=false};a.Ac=function(d){c.qb.add(d);h.c.log("register odb for "+d.aa());a.k()};a.pd=function(d){a.wb(d.g,d.q());a.k()};a.u=function(){c.qb.Ad();c.Ka.H()};a.I=function(){c.U=h;return c};a.i(OBR);return a}();OBR.f=OBR.f||function(){var c,a={},h={},d;h.kb="manualDataReady";h.jb="manualClickReady";a.i=function(f){c=f;d=new OBR.Q};a.I=function(){return h};h.ld=function(f){c.c.log("rec "+f+" was rendered");var g=c.h[f];g.T(true);g.t.Qf();f===0&&c.a.Ff();h.Ne(g)&&h.Df(g)};h.le=function(f){return Math.floor(Math.random()*f)+1};h.Ne=function(f){var g=f.l("widgetStatistics",false),i=c.b.Ga,j=f.l("tracking",false);if(!g||i||j)return false;f=f.l("wsSampling",0);if(f===0)return true;return h.le(f)===f};h.Df=function(f){c.e.ac(c.e.j.ua)===
2&&c.e.ac(c.e.j.ga)===2?c.p.Hb(f.g):c.e.L(c.e.j.ga,function(){c.e.L(c.e.j.ua,function(){c.p.Hb(f.g)},this)},this)};h.dg=function(f){c.c.log("widget was found");f=c.Ra.kd(f);f.g===0&&h.qd();f.Ee()===true?c.c.log("Dynamic loader - stop odb!"):c.r.Ac(f)};a.qc=function(f,g){var i="NA",j=f&&f.response?f.response:null,k;if(k=c.a.bb(g)){d.k("onmManualOdbReturned_"+g,j,g);if(k.ca())return}if(j&&j.request&&j.request.widgetJsId)i=j.request.widgetJsId;c.r.wb(g,i);if(k&&j&&j.documents){k.T(true);a.Wb(h.kb,g,
i,f)}c.r.k()};a.df=function(f,g){d.add("onmManualOdbReturned_"+f,g)};a.Wb=function(f,g,i,j){f=f+g+i;d.k(f,j.response.documents,g);d.oa(f)};a.oc=function(f,g){if(f!==null){var i=0,j=f.permalink,k=f.widgetId,l=f.widgetType,q=f.fbk;f=f.timeout;if(j&&typeof j==="string"&&k&&typeof k==="string"){c.c.log("manual Odb call");i=a.Se(j);a.Ja(h.kb+i+k,g);g=c.Ra.Pb(i,j,k,false,l,q,f,true);g.Kf("japi");c.ma[i]=g;d.k("onmManualOdbCall",g,h.kb);c.D.Lc(true);c.r.Ac(g)}}};a.Ja=function(f,g){d.add(f,g)};a.hf=function(f){d.add("onmManualOdbCall",
f)};a.Se=function(f){var g=0,i=c.b;if(i.la===null)i.la=c.h.length>0?c.h[0].aa():null;if(i.la===f)g=i.nc+1;else i.la=f;return i.nc=g};a.mc=function(f,g){c.a.hb();typeof g==="function"&&d.add(h.jb,g);if(f!==null)if((f=f.link)&&typeof f==="string"){c.c.log("manual Click");if(f.match(/http:\/\/.+outbrain.com/i)!==null)c.a.xd(f+"&noRedirect=true");else throw"Wrong redirect link: "+f;d.k(h.jb);d.oa(h.jb)}};h.Me=function(f){return h.hc(f)||f.l("stopWidget",false)};h.hc=function(f){return f.l("stopRater",
false)};function b(){c.c.log("ping success");c.D.Lc(true);c.display.Ze(h.ld);c.r.k()}function e(){c.c.log("ping fail")}h.qd=function(){c.D.ff(b);c.D.ef(e);if(c.b.We||c.b.ic){c.c.log("async - no ping");b()}else c.D.mf()};a.pb=function(f,g){var i,j;OBR.c.log("HTML returned");if(i=c.h[g]){i.t.Mf();if(!i.ca()){i.setData(f);j=i.q();if(!h.Me(i)){c.r.Ef(f.response.settings.apv);a.Le(i)?a.ea(g):a.qe(i);j&&d.k("odbRtn_"+j,i)}}a.Sd(i)}else c.c.log("odbHtmlReturned : Widget not found")};a.Sd=function(f){if(!h.hc(f)){c.r.wb(f.g,
f.q());c.r.k()}};a.Le=function(f){var g=true;if(f.kc()||f.fc())g=false;return g};a.qe=function(f){var g=f.g;if(f.kc())c.e.L(c.e.j.Va,function(){c.Qa.Ed(g)},this);else f.fc()&&c.display.xe(f)};a.ea=function(f){c.display.ea(c.h[f]);c.c.log("HTML - Render");a.pf(f)};a.pf=function(f){c.a.yd(f)};a.yc=function(f,g){c.a.hd(g,"ob_clicked");f=c.a.B(g,"data-redirect");if(f!==null)g.href=f;return true};a.zc=function(f){c.p&&c.p.tc();c.Z.Qd(f);return true};a.u=function(){d.H()};a.Fc=function(){c.Z.$e(h.dg);c.b.Ia?
c.b.Yf():c.Z.Tb()};a.td=function(f,g,i){if(confirm("Removing this recommendation will remove it permanently for this section and will refresh the recommendations.\n Are you sure you want to remove this recommendation?")){var j="https://web.archive.org/web/20130607073046/https://my.outbrain.com/manage/";c.c.log("isAd = "+i+" type = "+typeof i);j+=i===0?"add-zapped-document?publisherId="+g+"&docUrl="+c.a.P(f):"add-rule?publisherId="+g+"&ruleValue="+c.a.P(f)+"&ruleType="+i;f=c.a.z("ob_odbCall_cancelRec",j,true);c.a.v(f,false)}};a.sd=function(f){if(confirm("Removing this recommendation will remove it permanently for this section and will refresh the recommendations.\n Are you sure you want to remove this recommendation?")){f=
c.a.z("ob_odbCall_cancelRec",c.b.ob+c.b.ud+f+"&index=1&templateIndex=1&sig="+c.b.Tc,true);c.a.v(f,false)}};a.Af=function(f){!f||!f.ob_exclude_resp||!f.ob_exclude_resp.code||f.ob_exclude_resp.code===1||a.zc()};a.Bc=function(f,g){if(g&&typeof g==="function"){var i="odbRtn_"+f;d.add(i,g);(f=c.zb.cc(f))&&f.Ce()&&d.k(i,f)}};a.Xd=function(f){if(f=c.zb.cc(f))return f.C("tcr",-1);return null};a.zf=function(){c.Z.Tb()};a.H=function(){c.p&&c.p.tc();c.display.u();c.r.u();c.D.u();this.u();c.Z.u();c.W&&c.W.u();
c.b.va=false};a.vf=function(){this.H();this.Fc()};a.i(OBR);return a}();OBR.display=OBR.display||function(){var c,a={},h;a.i=function(d){c=d;h=new c.Q};a.dc=function(d,b){d=c.a.Zf(d);if((b=c.a.$(b.g))&&d&&d.length>0){b.innerHTML="";c.a.gb(d[0],b);c.c.log("element inserted")}};a.Ag=function(d){h.add("beforeRender",d)};a.Ze=function(d){h.add("afterRender",d)};a.xe=function(d){OBR.e.L(OBR.e.j.ga,c.a.X(),this);OBR.e.L(OBR.e.j.Sa,function(){a.Td(d)},this)};a.Td=function(d){a.dc(OBR.xa.ue(d),d);OBR.xa.i();h.k("afterRender",d.g)};a.ea=function(d){c.c.log("HTML - render widget with "+
d.ab());a.dc(d.ab(),d);d.T(true);h.k("afterRender",d.g)};a.u=function(){h.H()};a.i(OBR);return a}();OBR.Rc=OBR.Rc||function(c){var a={},h={},d=[],b={},e="",f=null,g=null,i=false,j=0,k="html",l=false,q=4E3,o="nano",s=false,w=false,v={};a.ig=0;a.hg=1E3;a.fg=2;a.g=c;a.wa="";a.t={sc:-1,rc:-1,Ec:-1,Ba:function(){var m=[];m.push(a.t.sc);m.push(a.t.rc);m.push(a.t.Ec);return m},Nf:function(){a.t.sc=(new Date).getTime()},Mf:function(){a.t.rc=(new Date).getTime()},Qf:function(){a.t.Ec=(new Date).getTime()}};a.Od={slow:6E3,normal:4E3,fast:2E3,qa:5};a.setData=function(m){var u;if(m&&m.response){m=m.response;
if(m.documents){u=m.documents;if(u.doc)d=u.doc}if(m.request)b=m.request;if(m.settings)h=m.settings;if(m.html)e=m.html;l=true}};a.ne=function(){return h};a.l=function(m,u){m=h[m];if(typeof m!=="undefined"&&m!==null)return m;return u};a.C=function(m,u){if(m=b[m])return m;return u};a.ab=function(){return e};a.q=function(){return f};a.Tf=function(m){f=typeof m==="string"?m:"NA"};a.Kf=function(m){k=m};a.de=function(){return k};a.Eg=function(m){j=m};a.pg=function(){return j};a.aa=function(){return g};a.Pf=
function(m){g=m};a.Ee=function(){return i};a.Hf=function(m){i=m==="true"||m===true};a.fc=function(){return a.l("displayMode","")==="flyThrough"};a.kc=function(){return a.l("displayMode","")==="video"};a.Ce=function(){return l};a.oe=function(){return o};a.Uf=function(m){if(typeof m==="string")o=m.toLowerCase()};a.Sf=function(m){if(typeof m==="string"&&m!=="")a.wa=m};a.Fe=function(){return!isNaN(parseInt(a.wa))};a.ja=function(){var m;m=parseInt(a.wa,10);return a.Fe()&&typeof m==="number"&&m>=0&&m<10?
OBR.a.be(g,m):a.wa};a.ca=function(){return s};a.T=function(m){if(typeof m==="boolean")s=m};a.sg=function(){return o==="hp"};a.n=function(){return v};a.If=function(m){if(typeof m==="object")v=m};a.Ie=function(){return w};a.ce=function(){return q};a.Jf=function(m){q=a.Od[m]||4E3};a.Lf=function(m){if(typeof m==="boolean")w=m};return a};
OBR.Ra=OBR.Ra||function(){var c=OBR,a={},h=new OBR.Q;a.Pb=function(d,b,e,f,g,i,j,k){d=new c.Rc(d);d.Pf(b);d.Tf(e);d.Hf(f);d.Uf(g);d.Sf(i);d.Jf(j);typeof k==="boolean"&&d.Lf(k);h.k("onWidgetCreate",d);return d};a.kd=function(d){var b=c.a.B(d,"data-src"),e=c.a.B(d,"data-widget-id"),f=c.a.B(d,"data-widget-type"),g=c.a.B(d,"data-timeout"),i=c.a.B(d,"data-fbk"),j=c.a.B(d,"data-advance-loader"),k=c.a.B(d,"data-dynLoad");c.a.w(d,"data-dynLoad","");c.b.Kc((j||"").toLowerCase()==="true");if(b===null)b=c.a.fe();
j=c.h.length===0&&c.b.la===b?1:c.h.length;b=a.Pb(j,b,e,k,f,i,g,false);c.h[j]=b;if(j===0){e=c.a.createElement("div","ob_holder");e.style.display="none";c.a.insertBefore(e,d);c.a.hb()}d.id=c.b.yb+j;return b};a.gf=function(d){h.add("onWidgetCreate",d)};return a}();OBR.zb=OBR.zb||function(){var c=OBR,a={};a.cc=function(h){var d,b,e;if(c.h){b=c.h.length;for(d=0;d<b;d+=1)if((e=c.h[d])&&e.q()===h)return e}return null};return a}();OBR.W=OBR.W||function(){var c={},a=OBR,h={},d={},b=new a.Q;d.Ld=function(i){h[i.g]=i;i.If({timeout:0,S:null,Jb:0,wd:false,Ye:false,Ja:"",Ea:false,ub:false,rb:false,V:false,Sc:"NA",reason:0});if(i.ja()!==""){OBR.r.cf(i,function(){e(i)});OBR.f.Bc(i.q(),c.bf)}};function e(i){var j;j=i.n();j.timeout=i.ce();if(!j.Ea)j.S=setTimeout(function(){var k=i.n();if(!i.ca()){k.reason=1;k.ub=true;g(i)}},j.timeout)}c.bf=function(i){var j=i.n();j.Ye=true;if(i.l("ispartialrecs",false)){clearTimeout(j.S);j.reason=3;
j.rb=true;g(i)}};c.af=function(i,j){if(i&&i.settings&&i.settings.ispartialrecs===true){i=a.a.bb(j);clearTimeout(i.n().S);f(i)}};a.Ra.gf(d.Ld);a.f.hf(function(i,j){i.n().Ja=j;a.f.df(i.g,c.af)});c.Kb=function(i,j){var k,l;if(!(i&&i.response))return false;k=i.response;OBR.c.log("Cdn response returned");j=(l=a.h[j])?l:a.a.bb(j);if(!j){a.c.log("Editorial Widget : Widget not found");return false}l=j.n();l.ib=i;if(k.request)l.Sc=k.request.widgetJsId||"NA";l.wd=(new Date).getTime();if(l.Ea&&!l.V){l.Ea=false;
l.V=true;f(j);c.Ta(j);clearTimeout(j.n().S)}else if(l.ub&&!l.V){l.ub=false;l.V=true;f(j);c.Ta(j);clearTimeout(j.n().S)}else if(l.rb&&!l.V){l.rb=false;l.V=true;f(j);c.Ta(j);clearTimeout(j.n().S)}return true};function f(i){var j=i.n();if(i.Ie()){i.T(true);a.f.Wb(j.Ja,i.g,j.Sc,j.ib)}else{i.setData(j.ib);OBR.f.ea(i.g)}a.r.pd(i)}c.Ta=function(i){var j,k,l;k=i.n();a.a.Je(i.ne())&&i.setData(k.ib);l=i.aa()!==""?a.a.P(i.aa()):window.location.href;j=i.l("irdfb","");if(j!==""){j+="&reason="+k.reason||"";j+=
"&url="+l||"";i=OBR.a.z("ironFallback"+i.g,j,false);OBR.a.v(i,true)}};function g(i){if(i.n().Jb===0){var j,k;j=a.b.vd;k=i.ja()+"_"+i.q()+"_"+i.g;j=j+k;k=a.a.z("ob_cdnCall_"+i.g,j,false);i.n().Jb=(new Date).getTime();a.a.v(k,true);a.c.log("fire this src "+j);a.c.log("CDN call: cdnCall")}}c.se=function(i){var j;if(i){j=i.n();clearTimeout(j.S);j.Ea=true;j.reason=2;g(i)}};c.u=function(){h=[];b.H()};c.I=function(){return d};return c}();if(OBR.b.ec===true){OBR.c.log("Widget Start!");OBR.b.ec=false;typeof window.OB_PASSIVE_MODE==="boolean"&&window.OB_PASSIVE_MODE===true?OBR.c.log("passive"):OBR.f.Fc()}
OBR.extern=OBR.extern||function(){var c=OBR,a={};a.getStat=function(){c.p.Gc()};a.showDescription=function(h,d){c.e.L(OBR.e.j.Ua,function(){OBR.wc.Qe(h,d)},this)};a.returnedHtmlData=function(h,d){c.f.pb(h,d)};a.returnedIrdData=function(h,d){c.W.Kb(h,d)};a.returnedJsonData=function(h,d){c.f.qc(h,d)};a.returnedError=function(h){OBR.c.log("Call made using extern class");c.c.log("Callback error"+h)};a.callRecs=function(h,d){OBR.c.log("Call made using extern class");c.f.oc(h,d)};a.callClick=function(h,
d){OBR.c.log("Call made using extern class");c.f.mc(h,d)};a.callWhatIs=function(h,d,b,e,f,g){OBR.e.L(OBR.e.j.ta,function(){OBR.xb.Ib(h,d,b,e,f,g)},this);return false};a.recClicked=function(h,d){OBR.c.log("Call made using extern class");c.f.yc(h,d)};a.imageError=function(h){OBR.c.log("Call made using extern class");c.a.Mb(h)};a.reloadWidget=function(){OBR.c.log("reload widget");c.f.vf()};a.researchWidget=function(){OBR.c.log("research widget");c.f.zf()};a.cancelRecommendation=function(h){OBR.c.log("cancel recommendation with bocr "+
h);c.f.sd(h)};a.cancelRecs=function(h,d,b){OBR.c.log("cancel recommendation by doc url "+h+" publisher id = "+d+" isAd = "+b);c.f.td(h,d,b)};a.refreshWidget=function(h){OBR.c.log("refresh widget");c.f.zc(h)};a.getCountOfRecs=function(h){return c.f.Xd(h)};a.onOdbReturn=function(h,d){c.f.Bc(h,d)};a.closeCard=function(){c.xa.Cd()};a.closeModal=function(){try{c.modal.hideModal()}catch(h){}};return a}();outbrain={};outbrain_rater=window.outbrain_rater===undefined?{}:window.outbrain_rater;
outbrain_rater.returnedHtmlData=function(c,a){OBR.f.pb(c,a)};outbrain_rater.returnedCancelOdbData=function(c){OBR.f.Af(c)};outbrain.returnedHtmlData=function(c,a){OBR.f.pb(c,a)};outbrain.returnedIrdJsonData=function(c,a){OBR.W.Kb(c,a)};outbrain.returnedJsonData=function(c,a){OBR.f.qc(c,a)};outbrain.returnedError=function(c){OBR.c.log("Callback error"+c)};outbrain.callRecs=function(c,a){OBR.f.oc(c,a)};outbrain.callClick=function(c,a){OBR.f.mc(c,a)};
outbrain.callWhatIs=function(c,a,h,d,b,e){OBR.e.L(OBR.e.j.ta,function(){OBR.xb.Ib(c,a,h,d,b,e)},this)};outbrain.recClicked=function(c,a){OBR.f.yc(c,a)};outbrain.imageError=function(c){OBR.a.Mb(c)};outbrain.closeModal=function(){try{OBR.modal.hideModal()}catch(c){}};

/*
     FILE ARCHIVED ON 07:30:46 Jun 07, 2013 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 14:45:56 Aug 29, 2019.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  RedisCDXSource: 32.271
  PetaboxLoader3.resolve: 80.0 (2)
  exclusion.robots.policy: 0.163
  LoadShardBlock: 339.531 (6)
  esindex: 0.018
  CDXLines.iter: 152.136 (3)
  load_resource: 99.31
  PetaboxLoader3.datanode: 205.049 (7)
  exclusion.robots: 0.176
*/